# Generated by Django 2.1 on 2020-09-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='BikeNo',
            field=models.CharField(help_text='ba.2.pa.2255', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='CitizenNo',
            field=models.CharField(help_text='05-02-71-00304', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='LiscenseNo',
            field=models.CharField(help_text='06-539235', max_length=20, unique=True),
        ),
    ]
