# Generated by Django 2.1 on 2020-09-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200922_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(default='abash', help_text='andy sherpa', max_length=20),
        ),
    ]
