# Generated by Django 2.1 on 2020-09-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_information_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(help_text='andy sherpa', max_length=20),
        ),
    ]
